### ISSUE TITLE
The main branch of safelife requires atleast gcc-10 for compilation

### ISSUE THREAD

**Issue by aseembits93** [PartnershipOnAI/safelife#26]
I'm on ubuntu 18.04 which ships with gcc-7 by default. I could build the version 1.0 release branch but was having a hard time building the main branch. Hope you can add this requirement to your README. Thanks!

**Comment by clwainwright** [comment]
@aseembits93 Thanks for pointing this out! And sorry for the troubles. I'm pretty sure the problem was with the very last commit on the master branch which attempted to make it easier to install on macos, but evidently messed up things on linux. Could you take a look at PR #27 and let me know if that fixes your problem?

**Comment by aseembits93** [comment]
after modifying setup.py, I can successfully build it gcc version 7.5.0 on ubuntu 18.04!
